import '../models/estado.dart';

class EstadoRepository {
  static List<Estado> tabela = [
    const Estado(
        id: '1',
        bandeira: 'assets/images/estados/bandeira-acre-600x420.png',
        sigla: 'AC',
        nome: 'Acre',
        populacao: 906876,
        temperaturaMediaVerao: 27,
        temperaturaMediaInverno: 25,
        cidades: ['1', '2']),
    const Estado(
        id: '2',
        bandeira: 'assets/images/estados/bandeira-alagoas-600x400.png',
        sigla: 'AL',
        nome: 'Alagoas',
        populacao: 3365351,
        temperaturaMediaVerao: 27,
        temperaturaMediaInverno: 25,
        cidades: ['1', '2']),
    const Estado(
        id: '3',
        bandeira: 'assets/images/estados/bandeira-amapa-600x420.png',
        sigla: 'AP',
        nome: 'Amapá',
        populacao: 877613,
        temperaturaMediaVerao: 29,
        temperaturaMediaInverno: 27,
        cidades: ['1', '2']),
    const Estado(
        id: '4',
        bandeira: 'assets/images/estados/bandeira-amazonas-600x428.png',
        sigla: 'AM',
        nome: 'Amazonas',
        populacao: 4269995,
        temperaturaMediaVerao: 29,
        temperaturaMediaInverno: 27,
        cidades: ['1', '2']),
    const Estado(
        id: '5',
        bandeira: 'assets/images/estados/bandeira-bahia-600x400.png',
        sigla: 'BA',
        nome: 'Bahia',
        populacao: 14985284,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 25,
        cidades: ['1', '2']),
    const Estado(
        id: '6',
        bandeira: 'assets/images/estados/bandeira-ceara-600x420.png',
        sigla: 'CE',
        nome: 'Ceará',
        populacao: 9240580,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 27,
        cidades: ['1', '2']),
    const Estado(
        id: '7',
        bandeira: 'assets/images/estados/bandeira-distrito-federal-600x420.png',
        sigla: 'DF',
        nome: 'Distrito Federal',
        populacao: 3094325,
        temperaturaMediaVerao: 23,
        temperaturaMediaInverno: 19,
        cidades: ['1', '2']),
    const Estado(
        id: '8',
        bandeira: 'assets/images/estados/bandeira-espirito-santo-600x420.png',
        sigla: 'ES',
        nome: 'Espirito Santo',
        populacao: 4108508,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 23,
        cidades: ['1', '2']),
    const Estado(
        id: '9',
        bandeira: 'assets/images/estados/bandeira-goias-600x420.png',
        sigla: 'GO',
        nome: 'Goiás',
        populacao: 7206589,
        temperaturaMediaVerao: 26,
        temperaturaMediaInverno: 17,
        cidades: ['1', '2']),
    const Estado(
        id: '10',
        bandeira: 'assets/images/estados/bandeira-maranhao-600x400.png',
        sigla: 'MA',
        nome: 'Maranhão',
        populacao: 7153262,
        temperaturaMediaVerao: 29,
        temperaturaMediaInverno: 27,
        cidades: ['1', '2']),
    const Estado(
        id: '11',
        bandeira: 'assets/images/estados/bandeira-mato-grosso-600x420.png',
        sigla: 'MT',
        nome: 'Mato Grosso',
        populacao: 3567234,
        temperaturaMediaVerao: 29,
        temperaturaMediaInverno: 25,
        cidades: ['1', '2']),
    const Estado(
        id: '12',
        bandeira:
            'assets/images/estados/bandeira-mato-grosso-do-sul-600x420.png',
        sigla: 'MS',
        nome: 'Mato Grosso do Sul',
        populacao: 2839188,
        temperaturaMediaVerao: 26,
        temperaturaMediaInverno: 22,
        cidades: ['1', '2']),
    const Estado(
        id: '13',
        bandeira: 'assets/images/estados/bandeira-minas-gerais-600x420.png',
        sigla: 'MG',
        nome: 'Minas Gerais',
        populacao: 21411923,
        temperaturaMediaVerao: 24,
        temperaturaMediaInverno: 19,
        cidades: ['1', '2']),
    const Estado(
        id: '14',
        bandeira: 'assets/images/estados/bandeira-para-600x400.png',
        sigla: 'PA',
        nome: 'Pará',
        populacao: 8777124,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 27,
        cidades: ['1', '2']),
    const Estado(
        id: '15',
        bandeira: 'assets/images/estados/bandeira-paraiba-600x420.png',
        sigla: 'PB',
        nome: 'Paraíba',
        populacao: 4059905,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 26,
        cidades: ['1', '2']),
    const Estado(
        id: '16',
        bandeira: 'assets/images/estados/bandeira-parana-600x420.png',
        sigla: 'PR',
        nome: 'Paraná',
        populacao: 11597484,
        temperaturaMediaVerao: 22,
        temperaturaMediaInverno: 14,
        cidades: ['1', '2']),
    const Estado(
        id: '17',
        bandeira: 'assets/images/estados/bandeira-pernambuco-600x400.png',
        sigla: 'PE',
        nome: 'Pernambuco',
        populacao: 9674793,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 26,
        cidades: ['1', '2']),
    const Estado(
        id: '18',
        bandeira: 'assets/images/estados/bandeira-piaui-600x400.png',
        sigla: 'PI',
        nome: 'Piauí',
        populacao: 3289290,
        temperaturaMediaVerao: 31,
        temperaturaMediaInverno: 28,
        cidades: ['1', '2']),
    const Estado(
        id: '19',
        bandeira: 'assets/images/estados/bandeira-rio-de-janeiro-600x420.png',
        sigla: 'RJ',
        nome: 'Rio de Janeiro',
        populacao: 17463349,
        temperaturaMediaVerao: 27,
        temperaturaMediaInverno: 22,
        cidades: ['1', '2']),
    const Estado(
        id: '20',
        bandeira:
            'assets/images/estados/bandeira-rio-grande-do-norte-600x400.png',
        sigla: 'RN',
        nome: 'Rio Grande do Norte',
        populacao: 3560903,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 26,
        cidades: ['1', '2']),
    const Estado(
        id: '21',
        bandeira:
            'assets/images/estados/bandeira-rio-grande-do-sul-600x420.png',
        sigla: 'RS',
        nome: 'Rio Grande do Sul',
        populacao: 11466630,
        temperaturaMediaVerao: 25,
        temperaturaMediaInverno: 14,
        cidades: ['1', '2']),
    const Estado(
        id: '22',
        bandeira: 'assets/images/estados/bandeira-rondonia-600x420.png',
        sigla: 'RO',
        nome: 'Rondônia',
        populacao: 1815278,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 26,
        cidades: ['1', '2']),
    const Estado(
        id: '23',
        bandeira: 'assets/images/estados/bandeira-roraima-600x400.png',
        sigla: 'RR',
        nome: 'Roraima',
        populacao: 652713,
        temperaturaMediaVerao: 29,
        temperaturaMediaInverno: 27,
        cidades: ['1', '2']),
    const Estado(
        id: '24',
        bandeira: 'assets/images/estados/bandeira-santa-catarina-600x436.png',
        sigla: 'SC',
        nome: 'Santa Catarina',
        populacao: 11466630,
        temperaturaMediaVerao: 25,
        temperaturaMediaInverno: 17,
        cidades: ['1', '2']),
    const Estado(
        id: '25',
        bandeira: 'assets/images/estados/bandeira-sao-paulo-600x400.png',
        sigla: 'SP',
        nome: 'São Paulo',
        populacao: 46649132,
        temperaturaMediaVerao: 24,
        temperaturaMediaInverno: 17,
        cidades: ['1', '2']),
    const Estado(
        id: '26',
        bandeira: 'assets/images/estados/bandeira-sergipe-600x420.png',
        sigla: 'SE',
        nome: 'Sergipe',
        populacao: 2338474,
        temperaturaMediaVerao: 28,
        temperaturaMediaInverno: 25,
        cidades: ['1', '2']),
    const Estado(
        id: '27',
        bandeira: 'assets/images/estados/bandeira-tocantins-600x420.png',
        sigla: 'TO',
        nome: 'Tocantins',
        populacao: 1607363,
        temperaturaMediaVerao: 29,
        temperaturaMediaInverno: 26,
        cidades: ['1', '2']),
  ];
}
